{{- range $key, $value := .Values.processors }}
apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: {{ $key }}
  namespace: {{ $.Values.namespace }}
spec:
  jobTargetRef:
    parallelism: {{ $.Values.parallelism }}
    activeDeadlineSeconds: {{ $.Values.activeDeadlineSeconds }}
    ttlSecondsAfterFinished: {{ $.Values.ttlSecondsAfterFinished }}
    template:
      spec:
        containers:
        - name: {{ $key }}
          image: "{{ $value.image.repository }}/{{ $value.image.name }}:{{ $value.image.tag }}"
          imagePullPolicy: {{ $value.image.pullPolicy }}
          resources:
              {{- toYaml $value.resources | nindent 16 }}
          env:
            {{- range $envKey, $envValue := $value.env }}
            - name: "{{ $envKey }}"
              value: "{{ $envValue }}"
            {{- end }}
        restartPolicy: Never
    backoffLimit: 4
  pollingInterval: {{ $value.pollingInterval }}
  minReplicaCount: {{ $value.minReplicaCount }}
  maxReplicaCount: {{ $value.maxReplicaCount }}
  successfulJobsHistoryLimit: {{ $value.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ $value.failedJobsHistoryLimit }}
  triggers:
  - type: azure-servicebus
    metadata:
      namespace: {{ $value.namespace }}
      topicName: {{ $value.topicName }}
      subscriptionName: {{ $value.subscriptionName }}
      messageCount: "1"
    authenticationRef:
        name: {{ $value.authenticationRef }}
{{- end }}
    