apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-stac-collection
{{- with .Values.processors.staccollection }}
spec:
  replicas: 3
  selector:
    matchLabels:
      {{ toYaml .labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{ toYaml .labels | nindent 8 }}
    spec:
      serviceAccountName: "stac-svc-acct"
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: stac-collection
          image: "{{ $.Values.repository }}/{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          command: ['stac', 'processor', 'run', '--name', 'ingest_stac_collection']
          resources:
              {{- toYaml .resources | nindent 16 }}
          env:
            - name: DATA_STORAGE_ACCOUNT_KEY
              valueFrom:
                secretKeyRef:
                  name: storageaccountkey
                  key: StorageAccountKey
            - name: DATA_STORAGE_ACCOUNT_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: storageaccountconnectionstring
                  key: StorageAccountConnectionString
            - name: SERVICE_BUS_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: servicebusconnectionstring
                  key: ServiceBusConnectionString
            - name: AZURE_LOG_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: appinsightsconnectionstring
                  key: AppInsightsConnectionString
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgadminloginpass
                  key: PGAdminLoginPass
            {{- range $envKey, $envValue := .env }}
            - name: "{{ $envKey }}"
              value: "{{ $envValue }}"
            {{- end }}
          volumeMounts:
            - name: secrets-store-inline
              mountPath: "/mnt/secrets-store"
              readOnly: true
      volumes:
        - name: secrets-store-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-stac-keyvault-wi"
      restartPolicy: Always
{{- end }}