apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor-stac-collection
  namespace: pgstac
{{- with .Values.processors.staccollection }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{ toYaml .labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{ toYaml .labels | nindent 8 }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: stac-collection
          image: "{{ .image.repository }}/{{ .image.name }}:{{ .image.tag }}"
          imagePullPolicy: {{ .image.pullPolicy }}
          resources:
              {{- toYaml .resources | nindent 16 }}
          env:
            {{- range $envKey, $envValue := .env }}
            - name: "{{ $envKey }}"
              value: "{{ $envValue }}"
            {{- end }}
      restartPolicy: Always
{{- end }}