apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-stac-keyvault-wi
  namespace: {{ .Values.deploymentNamespace }}
spec:
  provider: azure
  secretObjects:
  - data:
    - key: StorageAccountKey
      objectName: StorageAccountKey
    secretName: storageaccountkey
    type: Opaque
  - data:
    - key: PGAdminLoginPass
      objectName: PGAdminLoginPass
    secretName: pgadminloginpass
    type: Opaque
  - data:  
    - key: StorageAccountConnectionString
      objectName: StorageAccountConnectionString
    secretName: storageaccountconnectionstring
    type: Opaque
  - data:  
    - key: ServiceBusConnectionString
      objectName: ServiceBusConnectionString
    secretName: servicebusconnectionstring
    type: Opaque
  - data:
    - key: AppInsightsConnectionString
      objectName: AppInsightsConnectionString
    secretName: appinsightsconnectionstring
    type: Opaque
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"          
    clientID: {{ .Values.userAssignedClientId }}
    keyvaultName: {{ .Values.keyVaultName }}
    cloudName: {{ .Values.cloudName }}
    objects:  |
      array:
        - |
          objectName: StorageAccountKey
          objectType: secret
        - |
          objectName: PGAdminLoginPass
          objectType: secret
        - |
          objectName: StorageAccountConnectionString
          objectType: secret
        - |
          objectName: ServiceBusConnectionString
          objectType: secret
        - |
          objectName: AppInsightsConnectionString
          objectType: secret
    tenantId: {{ .Values.tenantId }}