apiVersion: v1
kind: Service
metadata:
  name: app-stacfastapi
  namespace: {{ .Values.Namespace }}
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-dns-label-name: app-stacfastapi-{{ .Values.envCode }}
spec:
  type: LoadBalancer
  loadBalancerIP: {{ .Values.stacfastapi.privateIp }}
  ports:
    - name: "8082"
      port: 8082
      targetPort: 8082
  selector:
    app: app-stacfastapi
