apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: {{ .Values.userAssignedClientId }}
  labels:
    azure.workload.identity/use: "true"
  name: {{ .Values.serviceAccountName }}
